# Generated by Django 4.0.6 on 2022-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences_temp_awd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences_temp_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences_temp_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='raw',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentences_awd',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentences_edu',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentences_int',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
