# Generated by Django 4.0.6 on 2022-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_sentences_temp_awd_sentences_temp_edu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_awd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Count_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Count_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Precision_awd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Precision_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Precision_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recall_awd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recall_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recall_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentences_irr_awd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences_irr_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences_irr_int',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
