# Generated by Django 4.0.6 on 2022-09-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_awd_data_edu_data_int_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences_pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
